api_platform:
    title: API Platform for Horoshop Test Issue
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
    formats:
        json:
            mime_types: [ 'application/json' ]
