api_platform:
    title: API Platform for Horoshop Test Issue
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
        extra_properties:
            rfc_7807_compliant_errors: false
    formats:
        json:
            mime_types: [ 'application/json' ]
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
